runtime: python
env: flex
threadsafe: true
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
    python_version: 3

handlers:
- url: /.*
  script: app.app


env_variables:
    SQL_USER: austin
    SQL_PASSWORD: austin
    SQL_DATABASE: database
    INSTANCE_CONNECTION_NAME: austinbakkerblog:europe-west2:mydatabase1


beta_settings:
    cloud_sql_instances: "austinbakkerblog:europe-west2:mydatabase1"

# skip_files:
# - venv/*

automatic_scaling:
    max_num_instances: 1
    cool_down_period_sec: 180

resources:
 cpu: 0.2
 memory_gb: 0.6
 disk_size_gb: 10

health_check:
 enable_health_check: False
